<?php

namespace Forte\OsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DefeitosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefeitosRepository extends EntityRepository
{
}
