forte_book:
    resource: "@ForteBookBundle/Controller/"
    type:     annotation
    prefix:   /

forte_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

forte_os:
    resource: "@OsBundle/Resources/config/routing.yml"
    prefix:   /

#forte_catalogo:
#    resource: "@ForteCatalogoBundle/Resources/config/routing.yml"
#    prefix:   /

# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
# Colocado para FOSUserBundle:
 