<?php

namespace Forte\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findOneByIdJoinedToEndereco($id)
{
    $query = $this->getEntityManager()
        ->createQuery('
            SELECT b, a FROM ForteBookBundle:Book b
            JOIN b.endereco a
            WHERE b.id = :id'
        )->setParameter('id', $id);

    try {
        return $query->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    }
}
}
