<?php

namespace Forte\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaginasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginasRepository extends EntityRepository
{
}
